"""Shared schemathesis Phase-0 builder (GUI + CLI).

Prefilled defaults live here — by design there are NO UI knobs for these.
Rationale in comments; change values here, not in forms.

What it does per job:
  1. Writes job-local `schemathesis.toml` (auto-discovered via cwd):
     auth headers, rate-limit auto, bounded generation, SecLists payload
     dictionary (if $SECLISTS_DIR resolves) + the user's REAL id values
     bound to their path params (fixes synthetic-id 404s -> real BOLA tests).
  2. Returns the argv to run. Parses JUnit XML into fusion findings.
"""

from __future__ import annotations

import os
import shutil
import xml.etree.ElementTree as ET
from pathlib import Path

# ---- Prefilled defaults (edit here, not in UI) ----
MAX_EXAMPLES = 50          # per-operation cases; 243-op spec stays minutes-scale
RATE_LIMIT = "auto"        # follow server 429/Retry-After
PHASES = "fuzzing,stateful"  # skip examples/coverage phases for speed; nuclei covers baselines
TIMEOUT_S = 600            # hard kill per job so one API can't wedge the worker
DICT_PROBABILITY = 0.1    # SecLists payloads sampled for ~10% of string params
DICT_CAP = 300             # max payload lines baked into the job dict file
# Small, high-signal SecLists files only (big lists would explode runtime)
SECLISTS_FILES = (
    "Fuzzing/Databases/SQLi/quick-SQLi.txt",
    "Fuzzing/XSS/human-friendly/XSS-Jhaddix.txt",
)


def find_st_bin() -> list[str] | None:
    if shutil.which("schemathesis"):
        return ["schemathesis"]
    if shutil.which("uvx"):
        return ["uvx", "schemathesis"]
    return None


def resolve_seclists() -> Path | None:
    d = os.environ.get("SECLISTS_DIR", "")
    p = Path(d) if d else None
    if p is not None and p.is_dir():
        return p
    # common local checkouts next to this repo (never vendored inside it)
    for cand in (Path.home() / "SecLists", Path("/usr/share/seclists"),
                 Path(__file__).resolve().parent.parent / "SecLists"):
        if cand.is_dir():
            return cand
    return None


def _toml_str(v: str) -> str:
    return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'


def all_path_params(spec: dict) -> set[str]:
    out: set[str] = set()
    for item in ((spec or {}).get("paths") or {}).values():
        if not isinstance(item, dict):
            continue
        pools = [item.get("parameters") or []]
        for op in item.values():
            if isinstance(op, dict) and "parameters" in op:
                pools.append(op.get("parameters") or [])
        for pool in pools:
            for p in pool:
                if isinstance(p, dict) and str(p.get("in", "")).lower() == "path" and p.get("name"):
                    out.add(str(p["name"]))
    return out


def _bake_seclists_dict(job_dir: Path, seclists: Path) -> Path | None:
    """Build a libFuzzer-quoted dict file from curated SecLists payloads.

    schemathesis `from-file` requires quoted entries; raw SecLists lines would
    fail parsing, so we quote+escape here and cap the count for runtime.
    """
    lines: list[str] = []
    for rel in SECLISTS_FILES:
        f = seclists / rel
        if not f.is_file():
            continue
        try:
            for raw in f.read_text(encoding="utf-8", errors="ignore").splitlines():
                s = raw.strip()
                if not s or s.startswith("#"):
                    continue
                lines.append('"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"')
                if len(lines) >= DICT_CAP:
                    break
        except OSError:
            continue
        if len(lines) >= DICT_CAP:
            break
    if not lines:
        return None
    dest = job_dir / "st-seclists.dict"
    dest.write_text("# auto-baked from SecLists (curated, capped)\n" + "\n".join(lines) + "\n",
                    encoding="utf-8")
    return dest


def build_job_config(job_dir: Path, spec: dict, user_vars: dict,
                     header_lines: list[str], max_examples: int = MAX_EXAMPLES) -> dict:
    """Write schemathesis.toml (+dict files) into job_dir. Returns run info."""
    job_dir = Path(job_dir)
    seclists = resolve_seclists()
    parts = [
        "# auto-generated by Infinity fusion — prefilled, no UI knobs",
        f"rate-limit = {_toml_str(RATE_LIMIT)}",
        f"generation.max-examples = {int(max_examples)}",
        "",
        "[headers]",
    ]
    for line in header_lines:
        if ":" in line:
            k, v = line.split(":", 1)
            k, v = k.strip(), v.strip()
            if k and v:
                parts.append(f"{_toml_str(k)} = {_toml_str(v)}")
    dict_info: dict = {"seclists": None, "real_ids": []}
    dict_file = _bake_seclists_dict(job_dir, seclists) if seclists else None
    if dict_file is not None:
        parts += ["", '[dictionaries.seclists]', f"from-file = {_toml_str(dict_file.name)}",
                  "", "[generation.dictionaries]",
                  f"string = {{ dictionary = {_toml_str('seclists')}, probability = {DICT_PROBABILITY} }}"]
        dict_info["seclists"] = {"file": dict_file.name,
                                 "source": [str(seclists / r) for r in SECLISTS_FILES]}
    # Bind the user's REAL values to their path params (kills synthetic-404s)
    path_params = all_path_params(spec)
    bound = 0
    for k, v in (user_vars or {}).items():
        if k in path_params and str(v).strip():
            dname = f"ids_{k}"
            parts += ["", f"[dictionaries.{dname}]",
                      f"values = [{_toml_str(str(v).strip())}]",
                      "", "[parameters]",
                      f"{_toml_str('path.' + k)} = {{ dictionary = {_toml_str(dname)} }}"]
            dict_info["real_ids"].append(k)
            bound += 1
    (job_dir / "schemathesis.toml").write_text("\n".join(parts) + "\n", encoding="utf-8")
    return {"toml": "schemathesis.toml", "seclists_dir": str(seclists) if seclists else "",
            "dictionaries": dict_info, "real_ids_bound": bound}


def build_argv(st_bin: list[str], spec_file: str, report_dir: str,
               max_examples: int = MAX_EXAMPLES) -> list[str]:
    return [*st_bin, "run", spec_file, "--phases", PHASES,
            "--report", "junit", "--report-dir", report_dir,
            "--max-examples", str(int(max_examples))]


def junit_to_failures(junit_xml: Path) -> list[dict]:
    """Parse schemathesis JUnit XML into fusion-normalized failure dicts."""
    try:
        root = ET.parse(str(junit_xml)).getroot()
    except Exception:
        return []
    out = []
    for tc in root.iter("testcase"):
        bad = tc.find("failure")
        if bad is None:
            bad = tc.find("error")
        if bad is None:
            continue
        name = tc.get("name", "api-logic-failure")
        msg = (bad.get("message") or "") + "\n" + (bad.text or "")
        msg = msg.strip()[:500]
        out.append({"check": name, "message": msg or name,
                    "url": "", "method": "", "path": ""})
    return out
